### ISSUE TITLE
「點ㄦ」在蜀拼重慶裏用diar打不出來

### ISSUE THREAD

**Issue by AlienKevin** [Papnas/shupin#11]
用diar打出來只有一個選項：「嗲ㄦ」。用dianer打出來「點兒」，那個「兒」字也不對。
必須要打yi diar纔會出現「一點ㄦ」，然後把「一」給刪除。
`shupin.dict.yaml`裏面好像只有含有「點ㄦ」的詞語，但是沒有「點ㄦ」本身。
用法例句：我去大學收點ㄦ衣服。

**Comment by amorphobia** [comment]
「點ㄦ」是生词，没在词库里。先打 dianr 分别选 「點」 和 「ㄦ」，然后再打 dianr 就有 「點ㄦ」了。

**Comment by AlienKevin** [comment]
哦，明白了🙏  有考慮把嗲ㄦ改成點ㄦ嗎？這個嗲ㄦ好像沒聽過，點ㄦ貌似用的比較多一些。

**Comment by amorphobia** [comment]
关于词库的问题请大佬看看

**Comment by amorphobia** [comment]
添加词语的问题请直接提 pr 让大佬来审核
