### ISSUE TITLE
C, D, X, R作為發音開頭起什麼作用？

### ISSUE THREAD

**Issue by AlienKevin** [Papnas/shupin#13]
有時候用漢語拼音反查四川話，會出現C, D, X, R等開頭的發音，但是不清楚這些的作用是什麼？
像我反查「那」的時候，顯示的讀音是：Rle1和la4。這個開頭的R是起什麼作用？
另外：有沒有考慮在反查的時候用地方版本代替通用拼音？像我用蜀拼重慶就可以顯示重慶話裡「那」的讀音。

**Comment by amorphobia** [comment]
据我所知是特殊读音，不同的词典会用不同规则把大写字母给去掉或者把这个读音给去掉

**Comment by AlienKevin** [comment]
哦，有什麼文件解釋這些notation是什麼意思嗎？有的話我可以幫忙加點簡單的documentation。
另：我看到`shupin_congqing.scheme.yaml`裡面只有代替部分D開頭讀音的規則：
```
#特字部分
    - xform/Ddi/le/	#的字讀音
    - xform/Dqu4/qie4/	#去字讀音
```
其他的幾個大寫字母都沒有代替規則，然後我打字的時候遇到像「那」這樣的詞，就不知道怎麼打出來Rle1這種讀音。

**Comment by amorphobia** [comment]
针对重庆方案来说，首先匹配了

```yaml
    - xform/Ddi/le/	#的字讀音
    - xform/Dqu4/qie4/	#去字讀音
```

这两个特殊读音，所以只能用 le 打「的」不能用 di；只能用 qie 打「去」，不能用 qu

然后用

```
    - xform/D//	#特字標記略去
```

去掉了大写字母 D, 表示其它 D 标记的特字不作读音改变，比如「六	Dlu5」在重庆方案了就变成了 lu5

其余特字不去掉大写字母，所以理论上要打的话必须连同大写字母一起打，但大写字母不在字母表里，因此就无法打出。

**Comment by AlienKevin** [comment]
謝謝，明白了。在反查的時候能不能也過濾掉其餘大寫字母？避免用戶看到，不知道怎麼讀，又打不出來

例子：普通話反差「那」
<img width="296" alt="反查「那」" src="https://user-images.githubusercontent.com/22850071/164235802-3cb4b04a-63ed-4a74-9ae6-591a580b65c8.png">

reverse_lookup的時候可以把Rle1的讀音去掉

**Comment by AlienKevin** [comment]
> 我提了一个 pr 见 #14
> 
> 你也可以帮忙测试一下，如果OK的话我就合并

我剛測試了，相關的討論我寫在PR的thread裡面了
