### ISSUE TITLE
簡繁轉換問題

### ISSUE THREAD

**Issue by AlienKevin** [Papnas/shupin#18]
如圖，「沙坪垻」的「垻」在簡體模式下沒有轉換為簡體的「坝」：
<img width="265" alt="沙坪坝" src="https://user-images.githubusercontent.com/22850071/164737580-29956c0c-d0a7-4b83-bd7e-8d63a693ee19.png">

**Comment by amorphobia** [comment]
使用最新 librime 未復現次問題，應該已經被上游的 OpenCC 修復掉了
