### ISSUE TITLE
「呆」在西南官話口語裏有另一個讀音 /âi/

### ISSUE THREAD

**Issue by amorphobia** [Papnas/shupin#2]
如重慶話的「腦殼呆」讀作 /lào kô âi/

事實上，「呆」字過去在普通話裏面也有 [ái] 這個讀音，「呆板」在過去應讀作 [ái bǎn]，只是讀 [dāi bǎn] 的人多了，審音的時候就規定讀 [dāi bǎn] 了。

但是在西南官話裏，/âi/ 的讀音一直存在，請考證添加。

**Comment by Papnas** [comment]
十分感謝支持。已增加相關字音 呆ai2 獃ai2 騃ai2。
歡迎你老也來參與維護

**Comment by amorphobia** [comment]
感謝！
我只是重慶話的母語使用者，沒有學術方面的知識，有的問題可能只是我的疑問，更多的是希望可以討論和得到解答，不知該不該用 issue 的形式提出來。

**Comment by amorphobia** [comment]
Fixed with commit 9121b7c01e871b1b56e8b16d87c95d87498b94db
