### ISSUE TITLE
「齿」字声调

### ISSUE THREAD

**Issue by amorphobia** [Papnas/shupin#6]
重庆话里「齿」字在我印象里应该是阳平，我在网上搜寻无果，未找到相关证据，因此开此议题进行讨论。

**Comment by Cyphotis** [comment]
我查巴縣是讀cì的。我處也是讀cì。

**Comment by Cyphotis** [comment]
成都好像有變調讀成陰平的

**Comment by Papnas** [comment]
《西蜀方言》《蜀法詞典》都只錄上聲，建議以上聲爲準。陽平可能是輕聲

**Comment by amorphobia** [comment]
感謝指點，如此說來陽平是輕聲的可能性比較大。

請問您提到的這兩個文獻在哪裏可以查閱？謝謝

**Comment by Papnas** [comment]
已新建了一个仓库放书
